gember_event_sourcing:
  cache:
    enabled: true
    psr6:
      service: '@cache.app'
  registry:
    event:
      reflector:
        path: '%kernel.project_dir%/src/Domain'
    command_handler:
      reflector:
        path: '%kernel.project_dir%/src/Domain'
  message_bus:
    symfony:
      event_bus: '@event.bus'
      command_bus: '@command.bus'
  event_store:
    rdbms:
      doctrine_dbal:
        connection: '@doctrine.dbal.default_connection'
  generator:
    identity:
      service: '@gember.identity_generator_symfony.uuid.symfony_uuid_identity_generator'
  serializer:
    symfony:
      serializer: '@serializer'
